export { default as ThinArrow } from "./thin-arrow/icon"
export { default as Check } from "./check/icon"
export { default as Close } from "./close/icon"
export * from "./types"

export { default as MarkerIcon } from "./marker.svg"
export { default as LogoIcon } from "./logo.svg"
export { default as SearchIcon } from "./search.svg"
export { default as CartIcon } from "./cart.svg"
export { default as WhatsappIcon } from "./whatsapp.svg"
export { default as InstagramIcon } from "./instagram.svg"